services:
  postgres-db:
    image: postgres:18-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: farmaceuticas_peru_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "@ChesterYPepe123"
    ports:
      - "5432:5432"
    volumes:
      - farmadata:/var/lib/postgresql

  backend-api:
    build: ./farmaceuticas-peru-back-end
    container_name: spring-backend
    ports:
      - "8081:8081"
    depends_on:
      - postgres-db
    environment:
      - DB_HOST=postgres-db
      - DB_NAME=farmaceuticas_peru_db
      - DB_USER=postgres
      - DB_PASSWORD=@ChesterYPepe123

  frontend-app:
    build: ./farmaceuticas-peru-front-end
    container_name: angular-frontend
    ports:
      - "80:80"
    depends_on:
      - backend-api

volumes:
  farmadata:
