services:
  # 1. BASE DE DATOS (PostgreSQL nativo en Render)
  - type: database
    name: postgres-db
    databaseName: farmaceuticas_peru_db
    user: farma_admin
    # Render genera contraseñas seguras automáticamente, pero puedes forzarla si tu backend la requiere fija
    plan: free 

  # 2. BACKEND (Spring Boot mediante Docker)
  - type: web
    name: backend-api
    env: docker
    dockerfilePath: ./farmaceuticas-peru-back-end/Dockerfile
    dockerContext: ./farmaceuticas-peru-back-end
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: postgres-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: postgres-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: postgres-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: postgres-db
          property: password
      - key: PORT
        value: 8081

  # 3. FRONTEND (Angular + Nginx mediante Docker)
  - type: web
    name: frontend-app
    env: docker
    dockerfilePath: ./farmaceuticas-peru-front-end/Dockerfile
    dockerContext: . # Mantenemos la raíz como contexto para que encuentre el nginx.conf externo
    plan: free
    envVars:
      - key: BACKEND_URL
        fromService:
          type: web
          name: backend-api
          property: url