server.port=8081

spring.application.name=fameceuticas-peru-back-end

spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres-db}:5432/${DB_NAME:farmaceuticas_peru_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:@ChesterYPepe123}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=YS12ZXJ5LWxvbmctYW5kLXNlY3VyZS1zZWNyZXQta2V5LWZvci1qd3QtdGhhdC1pcy1hdC1sZWFzdC0yNTYtYml0cw==
jwt.expiration=3600000