server.port=8081

spring.application.name=fameceuticas-peru-back-end

# --- VINCULACIÓN CON POSTGRESQL ---
# URL de conexión JDBC para PostgreSQL.
# farmacia_db es el nombre de la base de datos que debes crear.
<<<<<<< HEAD
spring.datasource.url=jdbc:postgresql://localhost:5432/farmaceuticas_peru_db

# Usuario y contraseña de tu servidor PostgreSQL local.
spring.datasource.username=postgres
spring.datasource.password=arm956250887
=======
spring.datasource.url=jdbc:postgresql://localhost:5433/farmaceuticas_peru_db

# Usuario y contraseña de tu servidor PostgreSQL local.
spring.datasource.username=postgres
spring.datasource.password=@ChesterYPepe123
>>>>>>> 47604d8edd03a1fe6b2f9de2ae829b06998cc97b

spring.datasource.driver-class-name=org.postgresql.Driver

# --- CONFIGURACIÓN DE JPA/HIBERNATE ---
# Le dice a Hibernate (la implementación de JPA) que use el dialecto correcto para PostgreSQL.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Muestra en la consola las consultas SQL que Hibernate genera. Muy útil para depurar.
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update

# --- JWT CONFIGURATION ---
# Secret key for signing JWTs. It should be a Base64 encoded string and be kept secret.
# Generate a new one for your production environment.
jwt.secret=YS12ZXJ5LWxvbmctYW5kLXNlY3VyZS1zZWNyZXQta2V5LWZvci1qd3QtdGhhdC1pcy1hdC1sZWFzdC0yNTYtYml0cw==
# Token expiration time in milliseconds (e.g., 3600000 for 1 hour)
jwt.expiration=3600000