spring.application.name=fameceuticas-peru-back-end

# --- VINCULACIÓN CON POSTGRESQL ---
# URL de conexión JDBC para PostgreSQL.
# farmacia_db es el nombre de la base de datos que debes crear.
spring.datasource.url=jdbc:postgresql://localhost:5432/farmaceuticas_peru_db

# Usuario y contraseña de tu servidor PostgreSQL local.
spring.datasource.username=postgres
spring.datasource.password=@ChesterYPepe123

# --- CONFIGURACIÓN DE JPA/HIBERNATE ---
# Le dice a Hibernate (la implementación de JPA) que use el dialecto correcto para PostgreSQL.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 'update': Hibernate intentará actualizar el esquema de la BD según tus clases Java.
# Ideal para desarrollo. Para producción se usa 'validate' o 'none'.
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola las consultas SQL que Hibernate genera. Muy útil para depurar.
spring.jpa.show-sql=true
